### ISSUE TITLE
Add budget capabilities to Spark connectivity to Cosmos DB 

### ISSUE THREAD

**Issue by dennyglee** [Azure/azure-cosmosdb-spark#139] opened 2017-11-17 14:18 UTC
Request: When connecting to CosmosDB, one could define a budget to use for the connection. And there would be several budgets (in my case two) defined for a CosmosDB collection, each with their own RU limits. I would set up, say, a budget called "API" and would give it 10k RUs and a budget called "Spark" and would give it 10k RUs. Then, when connecting with Spark, I would define that I would be using the "Spark" budget. And when connecting from API's, I would define using "API" budget. The solution to the GitHub issue is very similar, but it has an individual budget for each connection, while I still want to share budgets between connections while having several of budgets.

**Comment by tknandu** [comment] 2018-07-13 22:47
We've released new version of the Cosmos DB Spark connector targeting Spark 2.3 on Maven (https://search.maven.org/#artifactdetails%7Ccom.microsoft.azure%7Cazure-cosmosdb-spark_2.3.0_2.11%7C1.2.0%7Cjar)

Here you can specify a "WriteThroughputBudget" to specify the RU/s budget for the write workload

**Comment by nomiero** [comment] 2019-02-05 00:37
Duplicate of #111

**Closed by nomiero** 2019-02-05 00:37 UTC
Labels: enhancement

**Comment by wkeithvan** [comment] 2020-07-21 20:04
Can this feature please be documented? There is no mention of it on the [wiki](https://github.com/Azure/azure-cosmosdb-spark/wiki/Configuration-references).

**Comment by txl013** [comment] 2020-12-03 02:24
How do you specify, the `WriteThroughputBudget` config while writing the dataframe. I am passing this as `options` which takes `Map[String,String]`, but the write fails with exception. Have also tried passing with `option` parameter but still gives the same error.

```
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
        at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:101)
        at com.microsoft.azure.cosmosdb.spark.CosmosDBConnectionCache$.getOrCreateBulkExecutor(CosmosDBConnectionCache.scala:104)
        at com.microsoft.azure.cosmosdb.spark.CosmosDBConnection.getDocumentBulkImporter(CosmosDBConnection.scala:57)
        at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$.bulkImport(CosmosDBSpark.scala:264)
        at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$.com$microsoft$azure$cosmosdb$spark$CosmosDBSpark$$savePartition(CosmosDBSpark.scala:389)
        at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$$anonfun$1.apply(CosmosDBSpark.scala:152)
        at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$$anonfun$1.apply(CosmosDBSpark.scala:152)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:121)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$11.apply(Executor.scala:407)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1408)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:413)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)


```

**Comment by revinjchalil** [comment] 2020-12-03 02:36
The config value can be passed as string such as .option("WriteThroughputBudget ", "20000") or Map("WriteThroughputBudget" -> "20000")

**Comment by txl013** [comment] 2020-12-03 03:05
Hi @revinjchalil ,

Thanks for this. I have passed the same way, giving the exception mentioned above.
`inputDataset.write.mode(SaveMode.Overwrite).format("com.microsoft.azure.cosmosdb.spark").option("WriteThroughputBudget", 400).options(writeConfig).save()`

Also using,

```
val writeConfig: Map[String, String] = Map(
      "Endpoint" -> accountEndpoint,
      "Masterkey" -> accountKey,
      "Database" -> database,
      "Collection" -> collection,
      "Upsert" -> "true",
      "ConnectionMode" -> "Gateway",
      "WritingBatchSize" -> "1000",
      "WriteThroughputBudget" -> "1000")
```

Giving the class cast exception in all the ways using `option` or `options`.

```
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
        at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:101)
        at com.microsoft.azure.cosmosdb.spark.CosmosDBConnectionCache$.getOrCreateBulkExecutor(CosmosDBConnectionCache.scala:104)
        at com.microsoft.azure.cosmosdb.spark.CosmosDBConnection.getDocumentBulkImporter(CosmosDBConnection.scala:57)
        at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$.bulkImport(CosmosDBSpark.scala:264)
        at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$.com$microsoft$azure$cosmosdb$spark$CosmosDBSpark$$savePartition(CosmosDBSpark.scala:389)
        at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$$anonfun$1.apply(CosmosDBSpark.scala:152)
        at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$$anonfun$1.apply(CosmosDBSpark.scala:152)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
        at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:801)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:121)
        at org.apache.spark.executor.Executor$TaskRunner$$anonfun$11.apply(Executor.scala:407)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1408)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:413)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

I guess, the problem with the code where its not explicitly casting the string as Integer. or May be some other way to specify it, which is not documented.

**Comment by revinjchalil** [comment] 2020-12-03 04:03
It does not look like the latest uber jar that has the WriteThroughputBudget changes has taken effect in your environment. Would you cross check the version?

**Comment by txl013** [comment] 2020-12-03 05:17
Hi @revinjchalil ,

Thanks, looks like something wrong with the specific version `3.0.5`. azure-cosmosdb-spark_2.4.0_2.11-3.0.5-uber.jar
This version is only giving the above exception.

After your comment tried using other version like `3.6.1` ,`3.4.0` and `2.1.2`. All these are working.
azure-cosmosdb-spark_2.4.0_2.11-3.4.0-uber.jar
azure-cosmosdb-spark_2.4.0_2.11-2.1.2-uber.jar
azure-cosmosdb-spark_2.4.0_2.11-3.6.1-uber.jar

**Comment by revinjchalil** [comment] 2020-12-03 06:10
Yes, please use versions >= 3.4.0 that has the improved WriteThroughputBudget to limit the RU consumption during cosmosdb writes.

**Comment by txl013** [comment] 2020-12-18 04:37
Hi, @revinjchalil ,

Thanks for your response. I started to use, 3.6.1 version and "WriteThroughputBudget" is working. But i am experiencing a different issue, that the spark job is running very long and writing only records in 100 or even less per second at the end of the job(identified by querying the cosmos container manually with time interveal). Which is kind of drags the spark job to run longer. Even though there are available RUs, the spark job is writing data verly slowly. This is not the case when the "WriteThroughputBudget" is not put in the configuration.
Below is the Screen shot of how the RUs usage and request to cosmosdb drops and drags at the end of job.
![image](https://user-images.githubusercontent.com/18086828/102575217-cf844380-4146-11eb-8d1c-71649a3b0e57.png)

Is that i need to put any other configuration or am doing anything wrong.
