### ISSUE TITLE
Bulk Import API 

### ISSUE THREAD

**Issue by dennyglee** [Azure/azure-cosmosdb-spark#150] opened 2018-02-09 18:09 UTC
We've added the JARs for the `azure-cosmosdb-spark` connector (tagged as 1.1) to include the Bulk Import API.  Tasks that need to be done:
* Include more documentation on how to use it
* Update the releases folder to include all the necessary JARs (e.g. rx_java, documentdb jar, etc.).

To use the Bulk Import API, the config would look like:
```
val writeConfig = Config(Map(
  "Endpoint" -> "***",
  "Masterkey" -> "***",
  "Database" -> "***",
  "Collection" -> "***",
  "BulkImport" -> "true",
  "WritingBatchSize" -> "1000",
  "ConnectionMaxPoolSize" -> "100",
   “Upsert” ->  “true”))
```

**Comment by alrickdbritto** [comment] 2018-09-21 09:48
Hi,

I am facing he bulk import api error in spark cosmosdb connector.
i am using the 1.2.6 uber jar with spark 2.3.0

error seems to be like this.
18/09/21 09:08:19 ERROR Executor: Exception in task 0.0 in stage 22.0 (TID 25)
java.lang.Exception: Errors encountered in bulk import API execution. Exceptions observed:
[java.lang.RuntimeException: com.microsoft.azure.documentdb.DocumentClientException: {"Errors":["Encountered exception while executing function. Exception = JSRT error 0x30003"]}
ActivityId: e18ebda4-bd7d-11e8-90ec-032dc568ba7f, Request URI: /apps/9131100f-38cc-47f3-9b1a-fb55c528a04b/services/6a0847ad-e73c-4eae-98d4-f5151f4f77be/partitions/1203fb02-beee-4b92-b67b-4c0e4ac4d50e/replicas/131818494049782580p//, StatusCode: InternalServerError, SubStatusCode: ]
	at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$.bulkImport(CosmosDBSpark.scala:311)
	at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$.savePartition(CosmosDBSpark.scala:467)
	at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$.com$microsoft$azure$cosmosdb$spark$CosmosDBSpark$$savePartition(CosmosDBSpark.scala:408)
	at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$$anonfun$1.apply(CosmosDBSpark.scala:192)
	at com.microsoft.azure.cosmosdb.spark.CosmosDBSpark$$anonfun$1.apply(CosmosDBSpark.scala:183)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$26.apply(RDD.scala:847)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitionsWithIndex$1$$anonfun$apply$26.apply(RDD.scala:847)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
	at org.apache.spark.scheduler.Task.run(Task.scala:109)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:345)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by MingxuanLi** [comment] 2018-10-09 06:29
Same error here, any advice ?

**Comment by tknandu** [comment] 2018-10-09 06:31
@alrickdbritto @MingxuanLi This was caused by a regression scoped only to bulk importing data into non-partitioned/fixed collections (no partition key defined). We already have the fix being deployed across the globe and should be resolved within the next couple of days. 

In the interim, if you can create the collections with a partition key defined, you will not notice this error.

**Closed by tknandu** 2018-10-09 06:31 UTC
Labels: bug
